=== aspose-words/Aspose.Words-for-.NET/Examples/CSharp/Mail-Merge/Data/OrdersSchema.xsd
<?xml version="1.0" encoding ="utf-8"?>
<xs:schema id="OrdersSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Orders">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Order">
          <xs:complexType>
             <xs:sequence>
               <xs:element name="Number" type="xs:integer" />
               <xs:element name="Address" type="xs:string" />
               <xs:element name="Suburb" type="xs:string" />
               <xs:element name="City" type="xs:string" />
               <xs:element name="Phonenumber" type="xs:string"/>
               <xs:element name="Date" type="xs:string" />
               <xs:element name="Total" type="xs:decimal" />
               <xs:element name="Item">
                 <xs:complexType>
                   <xs:sequence>
                      <xs:element name="Name" type="xs:string" />
                      <xs:element name="Price" type="xs:decimal" />
                      <xs:element name="Quantity" type="xs:integer" />
                      <xs:element name="ItemTotal" type="xs:decimal" />
                      <xs:element name="CustomerPhone" type="xs:string" />
                   </xs:sequence>
                 </xs:complexType>
               </xs:element>
             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== aspose-words/Aspose.Words-for-.NET/Plugins/Aspose.Words Vs OpenXML Words/OpenXMLMissingFeatures/Missing Features of OpenXML Words v1.0/Mail Merge/Nested Mail Merge Regions/Data/CustomerData.xml
<?xml version="1.0" encoding="utf-8"?>
<Orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OrdersSchema.xsd">
  <Order>
    <Number>23</Number>
    <Address>Nelson Street</Address>
    <Suburb>Howick</Suburb>
    <City>Auckland</City>
    <Phonenumber>543 1234</Phonenumber>
    <Date>03/01/2010</Date>
    <Total>14.00</Total>
    <Item>
      <Name>BBQ Chicken Pizza</Name>
      <Price>6.00</Price>
      <Quantity>1</Quantity>
      <ItemTotal>6.00</ItemTotal>
    </Item>
    <Item>
      <Name>1.5 Litre Coke</Name>
      <Price>4.00</Price>
      <Quantity>2</Quantity>
      <ItemTotal>8.00</ItemTotal>
    </Item>
  </Order>
  <Order>
    <Number>10</Number>
    <Address>Parkville Avenue</Address>
    <Suburb>Pakuranga</Suburb>
    <City>Auckland</City>
    <Phonenumber>548 7342</Phonenumber>
    <Date>05/03/2010</Date>
    <Total>6.00</Total>
    <Item>
      <Name>Hawaiian Pizza</Name>
      <Price>4.00</Price>
      <Quantity>1</Quantity>
      <ItemTotal>4.00</ItemTotal>
    </Item>
    <Item>
      <Name>Fries</Name>
      <Price>1.00</Price>
      <Quantity>2</Quantity>
      <ItemTotal>2.00</ItemTotal>
    </Item>
  </Order>
</Orders>
